INSERT INTO cathedra (cathedra_id, name, department_department_id) VALUES (1, 'FI', 1);
INSERT INTO cathedra (cathedra_id, name, department_department_id) VALUES (21, 'Кафедра літературознавства', 1000);
INSERT INTO cathedra (cathedra_id, name, department_department_id) VALUES (31, 'Кафедра культурології', 1000);
INSERT INTO cathedra (cathedra_id, name, department_department_id) VALUES (41, 'Кафедра української мови', 1000);
INSERT INTO cathedra (cathedra_id, name, department_department_id) VALUES (51, 'Кафедра філософії та релігієзнавства', 1000);
INSERT INTO cathedra (cathedra_id, name, department_department_id) VALUES (61, 'Кафедра англійської мови', 1000);
INSERT INTO cathedra (cathedra_id, name, department_department_id) VALUES (71, 'Кафедра археології', 1000);
INSERT INTO cathedra (cathedra_id, name, department_department_id) VALUES (81, 'Кафедра історії', 1000);
INSERT INTO cathedra (cathedra_id, name, department_department_id) VALUES (91, 'Кафедра економічної теорії', 1001);
INSERT INTO cathedra (cathedra_id, name, department_department_id) VALUES (101, 'Кафедра фінансів', 1001);
INSERT INTO cathedra (cathedra_id, name, department_department_id) VALUES (111, 'Кафедра маркетингу', 1001);
INSERT INTO cathedra (cathedra_id, name, department_department_id) VALUES (121, 'Кафедра мультимедійних систем', 1002);
INSERT INTO cathedra (cathedra_id, name, department_department_id) VALUES (131, 'Кафедра інформатики', 1002);
INSERT INTO cathedra (cathedra_id, name, department_department_id) VALUES (141, 'Кафедра математики', 1002);
INSERT INTO cathedra (cathedra_id, name, department_department_id) VALUES (151, 'Кафедра мережних технологій', 1002);
INSERT INTO cathedra (cathedra_id, name, department_department_id) VALUES (161, 'Кафедра міжнародного права і спеціальних правових наук', 1003);
INSERT INTO cathedra (cathedra_id, name, department_department_id) VALUES (171, 'Кафедра загальнотеоретичних та державно-правових наук', 1003);
INSERT INTO cathedra (cathedra_id, name, department_department_id) VALUES (181, 'Кафедра галузевих правових наук', 1003);
INSERT INTO cathedra (cathedra_id, name, department_department_id) VALUES (191, 'Кафедра ім. Жана Моне з права Європейського Союзу', 1003);
INSERT INTO cathedra (cathedra_id, name, department_department_id) VALUES (201, 'Кафедра біології', 1004);
INSERT INTO cathedra (cathedra_id, name, department_department_id) VALUES (211, 'Кафедра екології', 1004);
INSERT INTO cathedra (cathedra_id, name, department_department_id) VALUES (221, 'Кафедра хімії', 1004);
INSERT INTO cathedra (cathedra_id, name, department_department_id) VALUES (231, 'Кафедра фізико-метематичних наук', 1004);
INSERT INTO cathedra (cathedra_id, name, department_department_id) VALUES (241, 'Кафедра лабораторної діагностики біологічних систем', 1004);
INSERT INTO cathedra (cathedra_id, name, department_department_id) VALUES (251, 'Кафедра фізичного виховання', 1004);
INSERT INTO cathedra (cathedra_id, name, department_department_id) VALUES (261, 'Кафедра зв’язків із громадськістю', 1005);
INSERT INTO cathedra (cathedra_id, name, department_department_id) VALUES (271, 'Кафедра психології та педагогіки', 1005);
INSERT INTO cathedra (cathedra_id, name, department_department_id) VALUES (281, 'Кафедра політології', 1005);
INSERT INTO cathedra (cathedra_id, name, department_department_id) VALUES (291, 'Кафедра соціології', 1005);