INSERT INTO subject (subject_id, final_type, name) VALUES (1, 1, 'політологія');
INSERT INTO subject (subject_id, final_type, name) VALUES (21, 0, 'англійська мова');
INSERT INTO subject (subject_id, final_type, name) VALUES (31, 0, 'українська мова');
INSERT INTO subject (subject_id, final_type, name) VALUES (41, 1, 'математика');
INSERT INTO subject (subject_id, final_type, name) VALUES (51, 1, 'історія');
INSERT INTO subject (subject_id, final_type, name) VALUES (61, 0, 'філософія');
INSERT INTO subject (subject_id, final_type, name) VALUES (71, 1, 'інформатика');
INSERT INTO subject (subject_id, final_type, name) VALUES (81, 1, 'основи психології');
INSERT INTO subject (subject_id, final_type, name) VALUES (91, 0, 'математичний аналіз');
INSERT INTO subject (subject_id, final_type, name) VALUES (101, 0, 'основи компютерних алгоритмів');
INSERT INTO subject (subject_id, final_type, name) VALUES (111, 0, 'диференціальні рівняння');
INSERT INTO subject (subject_id, final_type, name) VALUES (121, 1, 'веб програмування');
INSERT INTO subject (subject_id, final_type, name) VALUES (141, 1, 'культурологія');
INSERT INTO subject (subject_id, final_type, name) VALUES (151, 1, 'фізика');
INSERT INTO subject (subject_id, final_type, name) VALUES (161, 1, 'фізичне виховання');
INSERT INTO subject (subject_id, final_type, name) VALUES (171, 0, 'теорія ймовірності');