INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1, 'професор', ' БОНДАРЕНКО НІНА ВАСИЛІВНА', 21);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (11, 'доктор філологічних наук', ' КОВАЛЕНКО ОЛЕКСАНДР МИКОЛАЙОВИЧ', 21);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (21, 'кандидат філологічних наук', ' ЧОРНИЙ ВОЛОДИМИР ІВАНОВИЧ', 21);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (31, 'старший викладач', ' МОРОЗ ВІКТОР ІВАНОВИЧ', 21);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (41, 'кандидат філологічних наук', ' БОДНАР ВАСИЛЬ ІВАНОВИЧ', 21);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (51, 'старший викладач', ' САВЧУК МАРІЯ МИКОЛАЇВНА', 31);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (61, 'доктор філологічних наук', ' СЕМЕНЮК МИКОЛА ІВАНОВИЧ', 31);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (71, 'професор', ' ЛИСЕНКО СЕРГІЙ МИКОЛАЙОВИЧ', 31);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (81, 'старший викладач', ' ГОНЧАРЕНКО ВАЛЕНТИНА ІВАНІВНА', 31);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (91, 'старший викладач', ' ПОПОВ ВІКТОР ІВАНОВИЧ', 31);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (101, 'доцент', ' ЧОРНА ГАЛИНА ІВАНІВНА', 41);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (111, 'професор', ' МЕЛЬНИК ОКСАНА ІВАНІВНА', 41);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (121, 'доцент', ' КОВАЛЕНКО МАРІЯ ІВАНІВНА', 41);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (131, 'доктор філологічних наук', ' ШЕВЧУК КАТЕРИНА ІВАНІВНА', 41);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (141, 'професор', ' СОРОКА ВАСИЛЬ ІВАНОВИЧ', 41);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (151, 'професор', ' СИДОРЕНКО ОЛЕКСАНДР МИКОЛАЙОВИЧ', 51);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (161, 'кандидат філологічних наук', ' БОНДАРЕНКО ВАЛЕНТИНА ІВАНІВНА', 51);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (171, 'професор', ' КОВАЛЬЧУК ВАСИЛЬ ВОЛОДИМИРОВИЧ', 51);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (181, 'доцент', ' САВЧЕНКО ВАСИЛЬ ВАСИЛЬОВИЧ', 51);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (191, 'доцент', ' ЯКОВЕНКО МИКОЛА ІВАНОВИЧ', 51);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (201, 'професор', ' БОЙКО ТЕТЯНА ПЕТРІВНА', 61);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (211, 'кандидат філологічних наук', ' ТКАЧЕНКО ОЛЕКСАНДР ВІКТОРОВИЧ', 61);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (221, 'старший викладач', ' ГРИЦЕНКО МАРІЯ ІВАНІВНА', 61);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (231, 'професор', ' ІВАНОВ АНАТОЛІЙ МИКОЛАЙОВИЧ', 61);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (241, 'професор', ' ПЕТРОВА ГАЛИНА ІВАНІВНА', 61);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (251, 'старший викладач', ' ШВЕЦЬ НАТАЛІЯ ІВАНІВНА', 71);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (261, 'доцент', ' ШЕВЧУК СВІТЛАНА МИКОЛАЇВНА', 71);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (271, 'кандидат філологічних наук', ' ТАРАСЕНКО МИКОЛА ІВАНОВИЧ', 71);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (281, 'старший викладач', ' БОДНАР ВАСИЛЬ ІВАНОВИЧ', 71);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (291, 'старший викладач', ' ШЕВЧУК ВІКТОР ІВАНОВИЧ', 71);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (301, 'професор', ' ШЕВЧЕНКО ГАННА ГРИГОРІВНА', 81);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (311, 'старший викладач', ' ПЕТРЕНКО ВОЛОДИМИР ВАСИЛЬОВИЧ', 81);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (321, 'кандидат філологічних наук', ' ВОВК ОЛЕКСАНДР ІВАНОВИЧ', 81);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (331, 'професор', ' КОВАЛЕНКО СЕРГІЙ ГРИГОРОВИЧ', 81);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (341, 'доктор філологічних наук', ' КОВАЛЬ МАРІЯ ПЕТРІВНА', 81);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (351, 'професор', ' САВЧЕНКО МАРІЯ ВАСИЛІВНА', 91);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (361, 'кандидат економічних наук', ' ТКАЧУК АНАТОЛІЙ ВАСИЛЬОВИЧ', 91);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (371, 'старший викладач', ' ОЛІЙНИК ВАЛЕНТИНА МИКОЛАЇВНА', 91);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (381, 'доктор економічних наук', ' ТКАЧЕНКО ТЕТЯНА ВАСИЛІВНА', 91);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (391, 'професор', ' БОЙКО ОЛЕКСАНДР ОЛЕКСАНДРОВИЧ', 91);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (401, 'доктор економічних наук', ' МЕЛЬНИК СВІТЛАНА ВОЛОДИМИРІВНА', 101);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (411, 'доктор економічних наук', ' БОНДАР ГРИГОРІЙ ІВАНОВИЧ', 101);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (421, 'кандидат економічних наук', ' МИХАЙЛЕНКО ВАСИЛЬ ІВАНОВИЧ', 101);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (431, 'доцент', ' КОНОНЕНКО ВАЛЕНТИНА ІВАНІВНА', 101);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (441, 'доктор економічних наук', ' КРАВЧЕНКО ВАЛЕНТИНА ВОЛОДИМИРІВНА', 101);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (451, 'старший викладач', ' ШЕВЧЕНКО МАРІЯ ПЕТРІВНА', 111);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (461, 'професор', ' КОВАЛЬЧУК МИХАЙЛО ІВАНОВИЧ', 111);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (471, 'доцент', ' ОЛІЙНИК ВАСИЛЬ МИКОЛАЙОВИЧ', 111);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (481, 'професор', ' РУДЕНКО ІВАН ПЕТРОВИЧ', 111);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (491, 'професор', ' ПЕТРЕНКО ВАЛЕНТИНА МИКОЛАЇВНА', 111);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (501, 'старший викладач', ' МЕЛЬНИК НАТАЛІЯ ВАСИЛІВНА', 121);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (511, 'професор', ' ШЕВЧУК ВІКТОР ВОЛОДИМИРОВИЧ', 121);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (521, 'старший викладач', ' СЕРЕДА ВОЛОДИМИР МИКОЛАЙОВИЧ', 121);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (531, 'професор', ' КОВАЛЕНКО ТЕТЯНА ОЛЕКСАНДРІВНА', 121);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (541, 'доктор технічних наук', ' КОВАЛЬ СЕРГІЙ ІВАНОВИЧ', 121);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (551, 'доцент', ' КАРПЕНКО ВОЛОДИМИР ІВАНОВИЧ', 131);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (561, 'доцент', ' ТКАЧУК АНАТОЛІЙ ВАСИЛЬОВИЧ', 131);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (571, 'кандидат технічних наук', ' ТКАЧЕНКО ОЛЕКСАНДР ГРИГОРОВИЧ', 131);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (581, 'кандидат технічних наук', ' ІЩЕНКО ВОЛОДИМИР ВАСИЛЬОВИЧ', 131);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (591, 'старший викладач', ' ОЛІЙНИК ЛЮБОВ ІВАНІВНА', 131);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (601, 'доцент', ' ОСТАПЕНКО ГАННА ІВАНІВНА', 141);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (611, 'старший викладач', ' ОЛІЙНИК ГАЛИНА ВОЛОДИМИРІВНА', 141);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (621, 'доктор фізико-математичних наук', ' ТЕРЕЩЕНКО ВАЛЕНТИНА ІВАНІВНА', 141);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (631, 'професор', ' КРАВЕЦЬ ГАННА ВАСИЛІВНА', 141);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (641, 'доцент', ' ВАСИЛЕНКО ТЕТЯНА ІВАНІВНА', 141);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (651, 'професор', ' ОСТАПЕНКО МИКОЛА ІВАНОВИЧ', 151);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (661, 'кандидат фізико-математичних наук', ' КОВАЛЬОВ АНАТОЛІЙ ІВАНОВИЧ', 151);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (671, 'кандидат технічних наук', ' РОМАНЕНКО ВОЛОДИМИР ІВАНОВИЧ', 151);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (681, 'кандидат економічних наук', ' МОРОЗ ВАСИЛЬ ДМИТРОВИЧ', 151);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (691, 'доцент', ' ТКАЧ ІВАН ІВАНОВИЧ', 151);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (701, 'старший викладач', ' КИРИЧЕНКО СЕРГІЙ МИКОЛАЙОВИЧ', 161);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (711, 'професор', ' ВАСИЛЕНКО МАРІЯ ІВАНІВНА', 161);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (721, 'професор', ' БОНДАРЕНКО ВАЛЕНТИНА ВАСИЛІВНА', 161);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (731, 'старший викладач', ' БОНДАР ОЛЬГА ВАСИЛІВНА', 161);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (741, 'професор', ' ШЕВЧЕНКО СВІТЛАНА ІВАНІВНА', 161);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (751, 'професор', ' БОЙКО ІВАН ІВАНОВИЧ', 171);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (761, 'професор', ' БІЛОУС ВОЛОДИМИР ВАСИЛЬОВИЧ', 171);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (771, 'професор', ' ГОНЧАРЕНКО ТЕТЯНА ІВАНІВНА', 171);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (781, 'кандидат юридичних наук', ' КРАВЧЕНКО ЛІДІЯ ВАСИЛІВНА', 171);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (791, 'кандидат юридичних наук', ' КОСТЕНКО КАТЕРИНА ІВАНІВНА', 171);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (801, 'кандидат юридичних наук', ' ТКАЧЕНКО СЕРГІЙ ІВАНОВИЧ', 181);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (811, 'професор', ' ТКАЧЕНКО ЛЮБОВ МИКОЛАЇВНА', 181);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (821, 'доктор юридичних наук', ' САВЧУК ВАСИЛЬ МИКОЛАЙОВИЧ', 181);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (831, 'професор', ' РУДЕНКО ВОЛОДИМИР МИКОЛАЙОВИЧ', 181);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (841, 'кандидат юридичних наук', ' КУШНІР ОЛЬГА ІВАНІВНА', 181);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (851, 'старший викладач', ' СТЕПАНЕНКО ВАЛЕНТИНА ІВАНІВНА', 191);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (861, 'професор', ' ГОЛУБ ВОЛОДИМИР МИКОЛАЙОВИЧ', 191);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (871, 'професор', ' БОЙКО ВАЛЕНТИНА ВОЛОДИМИРІВНА', 191);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (881, 'старший викладач', ' ОЛІЙНИК ГАННА МИХАЙЛІВНА', 191);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (891, 'доктор юридичних наук', ' КОРНІЄНКО ЛЮБОВ ІВАНІВНА', 191);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (901, 'кандидат філософських наук', ' ІВАНОВА ЛЮДМИЛА ВАСИЛІВНА', 261);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (911, 'старший викладач', ' НІЖИНСЬКА МІСЬКА РАДА', 261);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (921, 'доцент', ' КРАВЧЕНКО ВАСИЛЬ ВАСИЛЬОВИЧ', 261);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (931, 'професор', ' МЕЛЬНИК ВАСИЛЬ СТЕПАНОВИЧ', 261);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (941, 'доцент', ' БОНДАР АНАТОЛІЙ ІВАНОВИЧ', 261);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (951, 'кандидат філософських наук', ' ХАРЧЕНКО ВАЛЕНТИНА ВАСИЛІВНА', 271);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (961, 'професор', ' ШАПОВАЛ ОЛЕКСАНДР МИКОЛАЙОВИЧ', 271);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (971, 'старший викладач', ' ТКАЧ МИХАЙЛО ІВАНОВИЧ', 271);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (981, 'кандидат філософських наук', ' ОЛІЙНИК ЛЮДМИЛА МИКОЛАЇВНА', 271);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (991, 'професор', ' ГРИЦЕНКО МАРІЯ ІВАНІВНА', 271);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1001, 'старший викладач', ' ПОПОВИЧ МИКОЛА ІВАНОВИЧ', 281);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1011, 'професор', ' КОНОНЕНКО ВАЛЕНТИНА МИКОЛАЇВНА', 281);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1021, 'доктор філософських наук', ' САВЧЕНКО ВОЛОДИМИР МИКОЛАЙОВИЧ', 281);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1031, 'старший викладач', ' БОЙКО ОЛЬГА ОЛЕКСАНДРІВНА', 281);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1041, 'старший викладач', ' ВАСИЛЕНКО ОЛЕКСАНДР ВОЛОДИМИРОВИЧ', 281);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1051, 'кандидат філософських наук', ' КОРНІЄНКО МАРІЯ ІВАНІВНА', 291);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1061, 'доцент', ' САЄНКО МИКОЛА ІВАНОВИЧ', 291);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1071, 'доцент', ' ОЛІЙНИК КАТЕРИНА ІВАНІВНА', 291);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1081, 'професор', ' МАЗУР МАРІЯ МИХАЙЛІВНА', 291);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1091, 'кандидат філософських наук', ' ІВАНОВА ЛЮДМИЛА МИКОЛАЇВНА', 291);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1101, 'професор', ' СЕМЕНЮК ВАСИЛЬ ІВАНОВИЧ', 201);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1111, 'доцент', ' СЕРДЮК ВАЛЕНТИНА ІВАНІВНА', 201);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1121, 'кандидат природничих наук', ' СЕМЕНЮК ВАСИЛЬ ІВАНОВИЧ', 201);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1131, 'професор', ' ШЕВЧЕНКО МАРІЯ АНДРІЇВНА', 201);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1141, 'професор', ' КЛИМЕНКО ВОЛОДИМИР ІВАНОВИЧ', 201);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1151, 'доктор природничих наук', ' КАРПЕНКО ВАЛЕНТИНА ВАСИЛІВНА', 211);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1161, 'доктор природничих наук', ' ШАПОВАЛОВА ВАЛЕНТИНА ІВАНІВНА', 211);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1171, 'професор', ' ЛИСЕНКО ОЛЕКСАНДР МИКОЛАЙОВИЧ', 211);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1181, 'доцент', ' ОНИЩЕНКО ВОЛОДИМИР ІВАНОВИЧ', 211);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1191, 'професор', ' ЛИСЕНКО ВІКТОР ВАСИЛЬОВИЧ', 211);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1201, 'старший викладач', ' КОЛОМІЄЦЬ ТЕТЯНА МИКОЛАЇВНА', 221);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1211, 'доцент', ' МЕЛЬНИК ЛЮБОВ ГРИГОРІВНА', 221);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1221, 'доктор природничих наук', ' КОВАЛЕНКО ОЛЕНА ВАСИЛІВНА', 221);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1231, 'доктор природничих наук', ' ВОВК ОЛЬГА МИКОЛАЇВНА', 221);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1241, 'доктор природничих наук', ' МЕЛЬНИК МИКОЛА ГРИГОРОВИЧ', 221);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1251, 'кандидат природничих наук', ' КОЛІСНИК ОЛЕКСАНДР МИКОЛАЙОВИЧ', 231);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1261, 'доктор природничих наук', ' ГОНЧАРОВ ВІКТОР ІВАНОВИЧ', 231);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1271, 'кандидат природничих наук', ' ШЕВЧУК МИХАЙЛО ІВАНОВИЧ', 231);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1281, 'кандидат природничих наук', ' САВЧУК ІВАН ВАСИЛЬОВИЧ', 231);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1291, 'кандидат природничих наук', ' ГОНЧАРЕНКО ВАЛЕНТИНА ІВАНІВНА', 231);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1301, 'доктор природничих наук', ' КОВТУН ТЕТЯНА ІВАНІВНА', 241);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1311, 'доцент', ' САВЧЕНКО МИКОЛА ГРИГОРОВИЧ', 241);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1321, 'доктор природничих наук', ' ТКАЧЕНКО МИХАЙЛО ІВАНОВИЧ', 241);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1331, 'доктор природничих наук', ' КАРПЕНКО ВАЛЕНТИНА МИКОЛАЇВНА', 241);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1341, 'доцент', ' МЕЛЬНИК ТЕТЯНА МИХАЙЛІВНА', 241);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1351, 'доктор природничих наук', ' КОВАЛЕНКО ЛЮДМИЛА ВАСИЛІВНА', 251);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1361, 'доцент', ' ПОЛІЩУК АНАТОЛІЙ МИКОЛАЙОВИЧ', 251);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1371, 'доцент', ' ШЕВЧЕНКО ВОЛОДИМИР ГРИГОРОВИЧ', 251);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1381, 'професор', ' ІВАНОВА ТЕТЯНА ВОЛОДИМИРІВНА', 251);
INSERT INTO professor (professor_id, academic_degree, full_name, cathedra_cathedra_id) VALUES (1391, 'кандидат природничих наук', ' КОСТЮК ОЛЬГА ІВАНІВНА', 251);